#### 함수 복습

In [12]:
# 소수 판별 알고리즘 만들기

cnadidatae_prime = int(input('숫자를 입력해주세요'))
def is_prime(candiate_prime):
    x = candiate_prime
    for i in range(2, x):
        if x % i == 0:
            print('소수아님')
        elif x % i !=0:
            print('소수임')
        
is_prime(1)

In [15]:
# 등수구하기 - 평균점수
score1 = [[80, 70], [90, 50], [40, 70], [50, 80]]
print(rank(score1)) # [1, 2, 4, 3]
 
score2 = [[80, 70], [70, 80], [30, 50], [90, 100], [100, 90], [100, 100], [10, 30]]
print(rank(score2)) # [4, 4, 6, 2, 2, 1, 7]
 
def rank(score):
    avg = [(i + j)/2 for i , j in score]
    avg_sort = sorted(avg, reverse = True)
    result = [avg_sort.index(i)+1 for i in avg]
    return result


[1, 2, 4, 3]
[4, 4, 6, 2, 2, 1, 7]


## 모듈

In [ ]:
# 파이썬 코드로 이루어진 파일을 모듈이라고 칭함.
# 함수나 변수, 클래스 등의 코드가 들어있음.
# 직접 만들거나, 다른사람 이 만들어 놓은 모듈(3rd party)을 가져와 사용함.
# 관련있는 모듈의 집합을 패키지라고 칭함
# 패키지는 모듈을 담는 디렉토리이며 파이썬 모듈을 꼐층적인 디렉토리 구조로 관리할 수 있게함.
# 모듈은 import라는 함수로서 가져올 수 있음.
# import 모듈명
# from 모듈명 import(함수 or 클래스명) = 이 명령어는 특정모듈의 특정부분만을 가지고 옴.
# import 모듈명 as 이름(별명)
# from 모듈명 import 이름(함수명 or 클래스명) as 이름(별명)
#  

#### 사용자 정의모듈

In [29]:
import importlib
import mymodule as mm

importlib.reload(mm)

print(mm.my_add(11,5))
print(mm.my_sub(11,5))

mymodule안에서의 __name__:mymodule
16
6


In [36]:
# 로또 번호 추첨기
import random

lotto = []

while len(lotto) < 6:
    num = random.randrange(1,46)
    if num not in lotto:
        lotto.append(num)
    

print(lotto)

[33, 28, 9, 45, 24, 30]


In [37]:
# 더 간단한 버전
random.sample([x for x in range(1,46,1)],6)

[12, 20, 26, 41, 14, 9]

### 클래스

In [ ]:
# 클래스란?
# 객체를 표현하기 위한 문법임, 여기서의 객체는 체크박스나, 스크롤바, 터틀객체 등의 특정한 모양이나 개념이 존재하는 것을 말함
# 현실세계 사물의 속성과 동작들을 코드로 구현하는 것임.
# 관련된 속성과 동작을 하나의 범주로 묶음.
# 사물의 속성은 변수로, 동작은 함수(메소드)로 표현함.
#   - 속성은 매개변수를 받아 사용하기 위한 값을 정하
#   - 메소드는 만들어진 속성을 이용해 그에 따른 동작을 실행함.
# 클래스를 구성하는 변수와 함수를 멤버라고 하며 클래스에 속한 함수를 메소드라고 한다.

In [ ]:
# 클래스는 똑같은 것을 께속 만들어 낼 수 있는 틀, 설계도 등으로 정의하기도 함.
# 클래스에서 찍어 낸 결과물을 객체라고 하며, 객체마다 고유한 성격을 가짐.
# 클래스의 인스턴스(instance)라고 표현하기도 함. 

In [38]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def walk(self):
        print(f'{self.name}이 걸어요')
        

In [40]:
person1 = Person("박지민", 31)
person1

In [ ]:
# 상속
class NewPerson(Person):
    def fly(self): #기능확장
        print(f'{self.name}이 날아요')
    def walk(self): # 매서드 오버라이딩
        print(f'{self.name}이 빨리 뛰어요')


In [47]:
person3 = NewPerson("민윤기", 33)
person3.fly()

민윤기이 날아요


In [50]:
class NewNewPerson(Person):
    def __init__(self, name, age, hobby):
        super().__init__(name, age)
        self.hobby = hobby
    
    def fly(self): #기능확장
        print(f'{self.name}이 날아요')
    
    def walk(self): # 매서드 오버라이딩
        print(f'{self.name}이 빨리 뛰어요')

    def introduce(self):
        print(f'{self.name}의 취미는 {self.hobby}입니다.')

In [51]:
person4 = NewNewPerson("김태형", 33 "노래부르기")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4024762561.py, line 1)

## 넘파이

In [52]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB 4.0 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/12.6 MB 7.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.5/12.6 MB 9.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.5/12.6 MB 12.2 MB/s eta 0:00:01
   ------------ --------------------------- 3.9/12.6 MB 15.4 MB/s eta 0:00:01
   ------------- -------------------------- 4.2/12.6 MB 15.8 MB/s eta 0:00:01
   ------------- -------------------------- 4.2/12.6 MB 15.8 MB/s eta 0:00:01
   ------------- -------------------------- 4.2/12.6 MB 15.8 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/12.6 MB 10.7 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 14.0 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 16.3 MB/s eta 0:00:01
   --


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [53]:
import numpy as np

In [54]:
np.__version__

'2.4.0'

In [55]:
alist = [1,2,3,4,5]

In [56]:
print(alist)
print(type(alist))

[1, 2, 3, 4, 5]
<class 'list'>


In [67]:
ar1 = np.array(alist)

In [70]:
ar1.shape

(5,)

In [60]:
print(ar1)
print(type(ar1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [61]:
ar1.dtype

dtype('int64')

In [62]:
ar2 = np.array([1.,2.,3.,4.,5.])

In [63]:
ar2.dtype

dtype('float64')

In [64]:
ar3 = np.array([1, 2.2,3.3,4,5])

In [66]:
print(ar3)
print(type(ar3))
ar3.dtype


[1.  2.2 3.3 4.  5. ]
<class 'numpy.ndarray'>


dtype('float64')

In [71]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [72]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
arr2.ndim

2

In [74]:
arr2.shape

(3, 4)

In [75]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
arr2.reshape(2,-1,3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
import time

size = 1_000_000
py_list = list(range(size))
np_array = np.array(size)

start_time = time.time()
result_list = [x * 2 for x in py_list]
end_time = time.time()
print(f'python list 연산:{end_time - start_time:5f}초')

start_time = time.time()
result_arrayy = np_array * 2
end_time = time.time()
print(f'numpy 배열연산: {end_time - start_time:5f}초')

python list 연산:0.032505초
numpy 배열연산: 0.000000초


In [95]:
import time
 
size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)
 
start_time = time.time()
result_list = [x * 2 for x in py_list]
end_time = time.time()
print(f'Python 리스트 연산: {end_time - start_time:.5f}초')
 
start_time = time.time()
result_array = np_array * 2
end_time = time.time()
print(f'Numpy 배열 연산: {end_time - start_time:.5f}초')

Python 리스트 연산: 0.03010초
Numpy 배열 연산: 0.00100초


In [97]:
data = [0,1,2,3,4,5,6,7,8,9]

answer = []
for i in data:
    answer.append(i*2)

answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [98]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
a = np.array([1,2,3])
b = np.array([10,20,30])




In [102]:
print(2 * a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [122]:
a = np.array([[0,1,2,4], [4,5,6,7]])


a[:, :2]

array([[0, 1],
       [4, 5]])

In [ ]:
a = np.array([0.1,2,3,4,5,6,7,8,9])
b = np.array([a % 2 == 0])


[[False  True False  True False  True False  True False]]


In [126]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])

a[idx]

array([11, 33, 55, 77, 99])

In [127]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,2])

a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33,
       33, 33])

In [165]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a[:,[True, False, False, True]]



array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [167]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,20])
print(a[a % 3 == 0])
print(a[a % 4 == 1])



array([ 1,  5, 13, 17])

In [172]:
x = np.arange(1,10001)
y = np.arange(10001,20001)
z = x + y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000], shape=(10000,))

In [174]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

%%time
z = x + y
z

CPU times: total: 0 ns
Wall time: 1.63 ms


UsageError: Line magic function `%%time` not found.
